<?php 
class Config{
	
	const NB_JOUR_PERTE_TERRITOIRE = 7;
	const NB_JETON_PERTE_TERRITOIRE = 1;
	const NB_MAX_DE_ATTAQUE = 3;
	const NB_MAX_DE_DEFENSE = 2;
	const NB_JOUR_TRANSFORMATION = 7;
	
	const VAL_DE_ATTAQUE = 6;
	const VAL_DE_DEFENSE = 6;
	
	const MAX_RENFORT_SECTEUR = 15;

	
	const XP_CHERCHE_OBJET = 1;
	const XP_USE_OBJET = 1;
	const XP_CAPTURE_SECTEUR = 40;
	const XP_RENFORT_SECTEUR = 10;
	const XP_ATTAQUE_SECTEUR = 10;
	const XP_JOUR_PAR_DISCIPLE = 5;
	const XP_PERTE_MORSURE_ENNEMI = 400;
	const XP_GRIMOIRE = 100;
	const XP_ECLAIREUR_HUMAIN = 65;
	
	const RACE_HUMAIN = 1;
	const RACE_HYBRIDE_LG =2;
	const RACE_HYBRIDE_VAMP = 3;
	const RACE_VAMPIRE = 4;
	const RACE_LOUP_GAROU = 5;
	const RACE_MAITRE_VAMPIRE = 6;
	const RACE_LYCAN_ALPHA = 7;
	
	const RACE_GROUPE_HUMAIN = 1;
	const RACE_GROUPE_VAMPIRE =2;
	const RACE_GROUPE_LOUP_GAROU = 3;
	
	const OBJET_ANTIDOTE =1;
	const OBJET_RECRUE = 2;
	const OBJET_GRIMOIRE = 3;
	const OBJET_ECLAIREUR_HUMAIN = 4;
}

?>